In [10]:
# read csv file and print out the data
import pandas as pd
import os

# read csv file
def get_year_data(file_path):
    data = pd.read_csv(file_path)
    # get unique year
    years = data["Year"].unique()
    # get missing years: 2000-2024
    missing_years = [str(year) for year in range(2000, 2026) if year not in years]

    # get type from file name between _ and .csv
    file_name = file_path.split("/")[-1]
    base_name = file_name.rsplit('_', 1)[0]
    type = file_name.split('_')[-1].split(".")[0]

    # convert to dataframe:
    row = {"Name": base_name}
    for year in years:
        row[str(year)] = type
    for year in missing_years:
        row[year] = "Missing"
    result_df = pd.DataFrame([row])

    # sort columns
    result_df = result_df[["Name"] + [str(year) for year in range(2000, 2026)]]

    return result_df

# list of csv files
file_list = os.listdir("../Data/CleanData/")
file_paths = ["../Data/CleanData/" + file for file in file_list]

In [11]:
get_year_data(file_paths[10])

,Name,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Botulism,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,...,mcd,mcd,mcd,mcd,mcd,mcd,mcd,mcd,mcd,Missing

In [12]:
import traceback

# analysis all files with error handling
result = pd.DataFrame()
for file_path in file_paths:
  try:
    df_row = get_year_data(file_path)
    result = pd.concat([result, df_row], ignore_index=True)
  except Exception as e:
    print(f"Error processing '{file_path}': {e}")
    traceback.print_exc()

# write to csv with error handling
try:
  result.to_csv("../Data/CheckData.csv", index=False)
  print(f"Saved result to ../Data/CheckData.csv, rows={len(result)}")
except Exception as e:
  print(f"Error writing CSV: {e}")
  traceback.print_exc()

Saved result to ../Data/CheckData.csv, rows=267

## test mcd functions

In [1]:
from pathlib import Path
import sys
import traceback
import pandas as pd

from CleanData import read_rtf, clean_text, text_to_dataframe_mcd

rtf_path = Path("../Data/GetData/Anthrax/mcd_Anthrax_46.rtf")
text, disease = read_rtf(rtf_path)
data, year = clean_text(text)
df = text_to_dataframe_mcd(data, year, disease)

In [2]:
print(df.head())

          Areas  Count Month   Type  Year  Disease
0         Total      0        Cases  2003  Anthrax
1  North Region      0        Cases  2003  Anthrax
2       Zone: 1      0        Cases  2003  Anthrax
3    Chiang Mai      0        Cases  2003  Anthrax
4    Chiang Rai      0        Cases  2003  Anthrax

In [3]:
df

             Areas  Count Month    Type  Year  Disease
0            Total      0         Cases  2003  Anthrax
1     North Region      0         Cases  2003  Anthrax
2          Zone: 1      0         Cases  2003  Anthrax
3       Chiang Mai      0         Cases  2003  Anthrax
4       Chiang Rai      0         Cases  2003  Anthrax
...            ...    ...   ...     ...   ...      ...
2751       Pattani      0   Dec  Deaths  2003  Anthrax
2752          Yala      0   Dec  Deaths  2003  Anthrax
2753      Zone: 19      0   Dec  Deaths  2003  Anthrax
2754         Satun      0   Dec  Deaths  2003  Anthrax
2755      Songkhla      0   Dec  Deaths  2003  Anthrax

[2602 rows x 6 columns]